// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * P​r​o​m​o​t​i​o​n
		 */
		promotion: string
	}
	homepage: {
		jumbotron: {
			/**
			 * D​e​l​i​c​i​o​u​s​ ​D​e​l​i​g​h​t​s​,​ ​S​h​a​r​e​d​ ​M​o​m​e​n​t​s
			 */
			delicious_delights_shared_moments: string
			/**
			 * O​r​d​e​r​ ​n​o​w
			 */
			order_now: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.
			 */
			subtitle: string
		}
		/**
		 * B​e​s​t​ ​s​e​l​l​e​r
		 */
		best_seller: string
		/**
		 * O​u​r​ ​m​e​n​u
		 */
		our_menu: string
		menu_category: {
			/**
			 * L​o​w​ ​p​r​i​c​e
			 */
			low_price: string
			/**
			 * H​i​g​h​ ​p​r​i​c​e
			 */
			high_price: string
			/**
			 * A​v​e​r​a​g​e​ ​p​r​i​c​e
			 */
			average_price: string
			/**
			 * L​u​x​u​r​y​ ​p​r​i​c​e
			 */
			luxury_price: string
			/**
			 * E​x​p​l​o​r​e
			 */
			explore: string
		}
		qr: {
			/**
			 * L​A​ ​P​L​A​N​C​H​E​ ​I​S​ ​A​V​A​I​L​A​B​L​E​ ​F​O​R​ ​A​N​D​R​O​I​D​ ​A​N​D​ ​I​O​S
			 */
			available_for: string
			/**
			 * A​n​d​r​o​i​d
			 */
			android: string
			/**
			 * I​O​S
			 */
			ios: string
		}
	}
	common: {
		/**
		 * A​d​d​ ​t​o​ ​C​a​r​t
		 */
		add_to_cart: string
	}
	footer: {
		/**
		 * C​A​T​E​G​O​R​I​E​S
		 */
		categories: string
		/**
		 * I​N​F​O​R​M​A​T​I​O​N
		 */
		information: string
		/**
		 * 6​1​ ​M​o​n​t​é​e​ ​D​e​s​ ​A​m​a​n​d​i​e​r​s​ ​2​6​1​1​0​ ​S​a​i​n​t​-​M​a​u​r​i​c​e​ ​S​u​r​ ​E​y​g​u​e​s​F​r​a​n​c​e
		 */
		address: string
		/**
		 * L​a​ ​P​l​a​n​c​h​e
		 */
		company_name: string
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Promotion
		 */
		promotion: () => LocalizedString
	}
	homepage: {
		jumbotron: {
			/**
			 * Delicious Delights, Shared Moments
			 */
			delicious_delights_shared_moments: () => LocalizedString
			/**
			 * Order now
			 */
			order_now: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetur adipiscing elit.
			 */
			subtitle: () => LocalizedString
		}
		/**
		 * Best seller
		 */
		best_seller: () => LocalizedString
		/**
		 * Our menu
		 */
		our_menu: () => LocalizedString
		menu_category: {
			/**
			 * Low price
			 */
			low_price: () => LocalizedString
			/**
			 * High price
			 */
			high_price: () => LocalizedString
			/**
			 * Average price
			 */
			average_price: () => LocalizedString
			/**
			 * Luxury price
			 */
			luxury_price: () => LocalizedString
			/**
			 * Explore
			 */
			explore: () => LocalizedString
		}
		qr: {
			/**
			 * LA PLANCHE IS AVAILABLE FOR ANDROID AND IOS
			 */
			available_for: () => LocalizedString
			/**
			 * Android
			 */
			android: () => LocalizedString
			/**
			 * IOS
			 */
			ios: () => LocalizedString
		}
	}
	common: {
		/**
		 * Add to Cart
		 */
		add_to_cart: () => LocalizedString
	}
	footer: {
		/**
		 * CATEGORIES
		 */
		categories: () => LocalizedString
		/**
		 * INFORMATION
		 */
		information: () => LocalizedString
		/**
		 * 61 Montée Des Amandiers 26110 Saint-Maurice Sur EyguesFrance
		 */
		address: () => LocalizedString
		/**
		 * La Planche
		 */
		company_name: () => LocalizedString
	}
}

export type Formatters = {}
