// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navbar: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * P​r​o​m​o​t​i​o​n
		 */
		promotion: string
	}
	homepage: {
		jumbotron: {
			/**
			 * D​e​l​i​c​i​o​u​s​ ​D​e​l​i​g​h​t​s​,​ ​S​h​a​r​e​d​ ​M​o​m​e​n​t​s
			 */
			delicious_delights_shared_moments: string
			/**
			 * O​r​d​e​r​ ​n​o​w
			 */
			order_now: string
		}
		/**
		 * B​e​s​t​ ​s​e​l​l​e​r
		 */
		best_seller: string
	}
}

export type TranslationFunctions = {
	navbar: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Promotion
		 */
		promotion: () => LocalizedString
	}
	homepage: {
		jumbotron: {
			/**
			 * Delicious Delights, Shared Moments
			 */
			delicious_delights_shared_moments: () => LocalizedString
			/**
			 * Order now
			 */
			order_now: () => LocalizedString
		}
		/**
		 * Best seller
		 */
		best_seller: () => LocalizedString
	}
}

export type Formatters = {}
